### ISSUE TITLE
Sample names for FASTQ data

### ISSUE THREAD

**Issue by rrydbirk** [LieberInstitute/10xPilot_snRNAseq-human#10]
Hi guys

Thanks for some nice and interesting work! I'm going through your raw data (FASTQ). I noticed some dobbelgängers among the names. This includes 
-Br5161_HPC and _HPC_suc
-Br5182_NAc and _NAc_reseq
-Br5287_DLPFC and _DLPFC_suc.

Which ones did you use? What does the "suc" and "reseq" refer to?

BR

Rasmus

**Comment by mattntran** [comment]
Hi Rasmus,

Sorry for the 'messy' directories and seemingly-redundant samples - we didn't create a cleaned up directory of files specifically for making public or anything.

You can ignore the two "_suc" samples - those were early iterations of processing aliquots of some of the first samples on a sucrose gradient + ultracentrifugation, as opposed to FACS enrichment of nuclei, which was used for the rest of the processing.

For the NAc sample, the 'Br5182_NAc_reseq' will be the correct one to use - in processing the sequenced library, that one (without the '_reseq') accidentally went through some adaptor trimming and so all the R1 lengths were scrambled, whereas they should all be a fixed length=28bp (i.e. 16bp 10x barcode + 12bp UMI).

Hope this helps,
Matt

**Comment by mattntran** [comment]
Sorry Rasmus, actually I should also note that that 'Br5287_DLPFC' sample in both cases yielded really poor quality nuclear transcriptomes in our QC and some preliminary clustering analyses - thus we actually omitted this sample in our preprint analyses.  We think it was just a poor quality tissue sample to begin with (but only for this brain region for this donor).

Regards,
Matt

**Comment by rrydbirk** [comment]
Hi Matt

Thanks for your thorough reply! I'll continue with this info.

/Rasmus
