### ISSUE TITLE
Raw counts matrix availability?

### ISSUE THREAD

**Issue by reliscu** [LieberInstitute/10xPilot_snRNAseq-human#8]
Hi there!

Apologies if you have already shared this data somewhere, but I was wondering if you could share the raw counts matrix for each region? It appears that you have thus far only shared the dimensionally reduced data and raw fastq files.

Thanks,
Rebecca

**Comment by mattntran** [comment]
Hi @reliscu, thanks for interacting with our project!

You can find the raw counts matrices in the `assays` slot of each of the `SCE` objects hosted under [this section of the README.md](https://github.com/LieberInstitute/10xPilot_snRNAseq-human#processed-data).  Simply call `assay(sce.name, "counts")` for the sparse matrix (type `dgCMatrix`).  These include gene-level (exon + intron) UMI counts for all nuclear barcodes that passed 'nucleus calling' & mito rate QC, but which hasn't removed those flagged as clusters potentially driven by doublets or by low total transcripts, which were intentionally kept for investigators to treat as desired.

You'll also find `"logcounts"` as another entry in that `assays` slot for each `SCE` (i.e. with `assay(sce.name, "logcounts")`), which is log2-transformed (, nuclear library size factor-normalized) counts. Hope this helps!

Regards,
Matt

**Comment by reliscu** [comment]
Ah, apologies! It was right in front of me.

Thanks so much for your quick reply.
