### ISSUE TITLE
Raw data availability

### ISSUE THREAD

**Issue by rrydbirk** [LieberInstitute/10xPilot_snRNAseq-human#9]
First, congratulations on your great work, I hope it's published soon!

When I try to access the raw data through Globus, I'm not allowed to download the data even though you claim they are publicly available. Do I need some sort of clearance to download the files? Also, is it possible to download using FTP or similar?

BR

Rasmus

**Comment by lcolladotor** [comment]
Hi Rasmus,

Can you provide more details please? Like what's the Globus endpoint you are using? From http://research.libd.org/globus/ are you using http://research.libd.org/globus/jhpce_tran2021/index.html which redirects to https://app.globus.org/file-manager?origin_id=e4e30efc-f166-11eb-ab64-d195c983855c&origin_path=%2F?

Best,
Leo

**Comment by rrydbirk** [comment]
Hi Leo

I've attached a screenshot. But yes, I seem to be using the path you describe.

BR

Rasmus

![image](https://user-images.githubusercontent.com/26813635/132634303-0694810d-9dc5-4aae-86ce-963bff8c0d99.png)

**Comment by lcolladotor** [comment]
Hi,

It seems to be working for you since you can see the files. On the far right you can click the blue link to “transfer or sync” all files. Alternatively you can do it for one file at a time. You’ll need to select a location where you have write access to download the files to. 

Best,
Leo

**Comment by rrydbirk** [comment]
Hi Leo

Indeed, now I got it to work through the client. Thanks a lot!

/Rasmus
